[package]
name = "instant-compiler"
version = "0.1.0"
authors = ["Tomasz Miśków <miskow.tomasz@gmail.com>"]
edition = "2018"

[lib]
name = "instant_compiler"
path = "src/lib.rs"

[dependencies]
parser = { path = "parser" }
compiler = { path = "compiler" }

